name: lume-orchestration-demo
channels:
  - conda-forge
dependencies:
  - Python=3.9
  - cx_Oracle
  - prefect
  - lume-model
  - sqlalchemy
  - pymysql
  - dependency_injector
  - click
  - sshtunnel
  - pymongo
  - pandas
  - importlib_metadata
  - jupyterlab
  - pip
