prefect-server: # https://github.com/PrefectHQ/server/blob/master/helm/prefect-server/values.yaml
    postgresql:
      servicePort: 5432
      postgresqlPassword: password
    agent:
      enabled: true 
    jobs:
      createTenant:
        enabled: true
model-db: # https://github.com/bitnami/charts/tree/master/bitnami/mysql/
  image:
    debug: true
  auth:
    username: root
    password: password
    rootPassword: password
results-db: # https://github.com/bitnami/charts/tree/master/bitnami/mongodb
  auth:
    username: root
    password: password
    rootPassword: password