prefect-server: # https://github.com/PrefectHQ/server/blob/master/helm/prefect-server/values.yaml
    postgresql:
      servicePort: 5432
      postgresqlPassword: password
    agent:
      enabled: true 
    jobs:
      createTenant:
        enabled: true
    apollo:
      service: 
        port: 4200
    ui: 
      service: 
         port: 8080
mysql: # https://github.com/bitnami/charts/tree/master/bitnami/mysql/
  image:
    debug: true
  auth:
    username: root
    password: password
    rootPassword: password
  primary:
    service: 
      port: 3306
mongodb: # https://github.com/bitnami/charts/tree/master/bitnami/mongodb
  auth:
    username: root
    password: password
    rootPassword: password
  service:
    port: 27017
  